
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python grader

on: [push]

permissions:
  contents: write

jobs:

  testing:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      continue-on-error: true
      run: |
        pytest ./.python/test_.py --junitxml=./.python/results.xml
        if [ -f ./.python/results.xml ]; then echo "results.xml created"; fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-results-artifact
        path: ./.python/results.xml


  grading:

    runs-on: ubuntu-latest

    outputs:
      grade: ${{ steps.python-grade.outputs.grade }}
      string: ${{ steps.python-grade.outputs.string }}
    
    needs: testing

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: my-results-artifact
        path: ./.python/dir

    - name: Restore file
      run:
        mv ./.python/dir/results.xml ./.python/results.xml
     
    - name: Grade
      id: python-grade
      run: |
        output=$(python ./.python/grade.py ./.python/results.xml)
        echo $output
        grade=$(echo "$output" | cut -d',' -f1)
        echo "grade=$grade" >> $GITHUB_OUTPUT
        string=$(echo "$output" | cut -d',' -f2)
        echo "string=$string" >> $GITHUB_OUTPUT




  Airtable:

    runs-on: ubuntu-latest

    needs: grading

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyairtable
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Update Airtable
      id: update-airtable
      env:
        AIRTABLE_PAT: ${{ secrets.AIRTABLE_PAT }}
        AIRTABLE_DB_ID: ${{ secrets.AIRTABLE_DB_ID }}
        AIRTABLE_TABLE_ID : ${{ secrets.AIRTABLE_TABLE_ID }}
      run: |
        python ./.python/updatedb.py ${{ needs.grading.outputs.grade }} ${{ needs.grading.outputs.string }}